@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

### AUTENTICAÇÃO

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "teste@hotmail.com",
	"password": "12345236"
}

### CRUD DE USUARIOS

# @name listAll_accounts
GET {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Gustavo novo teste 3",
	"email": "teste11@hotmail.com",
	"password": "12345236",
	"role": "administrador"
}

###

# @name update_account
Put {{baseUrl}}/accounts/b700875a-6e3a-469f-baab-23fe8ace42b9
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Teste 2"
}

###

# @name delete_account
Delete {{baseUrl}}/accounts/66a6f76a-23e1-45cf-bc73-5faa04c15df0
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

### CRUD DE SETORES

# @name listAll_accounts
GET {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_sector
POST {{baseUrl}}/sectors
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "VENDAS",
	"description": "setor de vendas da empresa crossconection"
}

###

### UPDATE DE AVATAR

###
# @name upload_avatar
POST {{baseUrl}}/upload-avatar
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer {{authToken}}

--boundary123
Content-Disposition: form-data; name="file"; filename="40045373.jpeg"
Content-Type: image/jpeg

< /home/gustavo/Imagens/40045373.jpeg
--boundary123--


###